-- ============================================================================
-- Robokalam Learner OS — COMPLETE SCHEMA, PHASES 2–9 (design reference, MySQL 8 / MariaDB 10.6+)
--
-- Phase 1 tables live in server/migrations/001_foundation.sql and are IMPLEMENTED.
-- Everything below is the agreed target design for later phases. Each phase ships its
-- own numbered migration containing ONLY its tables; this file is validated by applying
-- it on top of 001 (see docs/ARCHITECTURE.md §3). Conventions are identical:
--   * ids are VARCHAR(36) UUIDs generated by the app; org_id on every business table
--   * composite FKs (id, org_id) keep tenants apart
--   * learner activity is attached to learners(id) — NEVER copied per batch
--   * "partial unique" rules use generated columns that are NULL when the rule does not apply
--   * money is stored in paise (bigint); timestamps are UTC DATETIME(3)
-- ============================================================================

-- ------------------------------ PHASE 2: CLASSROOM -------------------------
CREATE TABLE subjects (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  course_id VARCHAR(36) NOT NULL,
  name VARCHAR(160) NOT NULL,
  position INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_subjects_id_org (id, org_id),
  CONSTRAINT fk_subjects_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_subjects_course FOREIGN KEY (course_id, org_id) REFERENCES courses (id, org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE topics (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  subject_id VARCHAR(36) NULL,
  title VARCHAR(200) NOT NULL,
  position INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_topics_id_org (id, org_id),
  KEY idx_topics_batch (batch_id, position),
  CONSTRAINT fk_topics_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_topics_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE classroom_posts (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  author_user_id VARCHAR(36) NOT NULL,
  kind VARCHAR(14) NOT NULL,
  title VARCHAR(255) NULL,
  body TEXT NULL,
  payload JSON NULL,
  comments_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_posts_id_org (id, org_id),
  KEY idx_posts_batch_time (batch_id, created_at),
  CONSTRAINT fk_posts_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_posts_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_posts_author FOREIGN KEY (author_user_id) REFERENCES users (id),
  CONSTRAINT chk_post_kind CHECK (kind IN ('announcement','assignment','material','video','link','poll','quiz'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE comments (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  post_id VARCHAR(36) NOT NULL,
  parent_comment_id VARCHAR(36) NULL,
  author_user_id VARCHAR(36) NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  KEY idx_comments_post (post_id, created_at),
  CONSTRAINT fk_comments_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_comments_post FOREIGN KEY (post_id, org_id) REFERENCES classroom_posts (id, org_id),
  CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments (id),
  CONSTRAINT fk_comments_author FOREIGN KEY (author_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE materials (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NULL,
  course_id VARCHAR(36) NULL,
  topic_id VARCHAR(36) NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  kind VARCHAR(8) NOT NULL,
  storage_key VARCHAR(300) NULL,
  external_url VARCHAR(1000) NULL,
  mime_type VARCHAR(100) NULL,
  size_bytes BIGINT NULL,
  uploaded_by VARCHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_materials_id_org (id, org_id),
  CONSTRAINT fk_materials_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_materials_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_materials_course FOREIGN KEY (course_id, org_id) REFERENCES courses (id, org_id),
  CONSTRAINT fk_materials_topic FOREIGN KEY (topic_id, org_id) REFERENCES topics (id, org_id),
  CONSTRAINT fk_materials_user FOREIGN KEY (uploaded_by) REFERENCES users (id),
  CONSTRAINT chk_material_kind CHECK (kind IN ('pdf','ppt','doc','image','video','link'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE videos (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  material_id VARCHAR(36) NOT NULL,
  provider VARCHAR(30) NOT NULL,
  provider_ref VARCHAR(300) NOT NULL,
  duration_seconds INT NULL,
  UNIQUE KEY uq_videos_id_org (id, org_id),
  CONSTRAINT fk_videos_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_videos_material FOREIGN KEY (material_id, org_id) REFERENCES materials (id, org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE video_progress (
  video_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  org_id VARCHAR(36) NOT NULL,
  seconds_watched INT NOT NULL DEFAULT 0,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (video_id, learner_id),
  CONSTRAINT fk_vp_video FOREIGN KEY (video_id, org_id) REFERENCES videos (id, org_id),
  CONSTRAINT fk_vp_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE assignments (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  topic_id VARCHAR(36) NULL,
  post_id VARCHAR(36) NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  instructions TEXT NULL,
  due_at DATETIME(3) NULL,
  max_marks DECIMAL(8,2) NOT NULL DEFAULT 100,
  allow_resubmit BOOLEAN NOT NULL DEFAULT FALSE,
  attachments JSON NULL,
  created_by VARCHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_assignments_id_org (id, org_id),
  KEY idx_assignments_batch_due (batch_id, due_at),
  CONSTRAINT fk_assign_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_assign_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_assign_user FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_assign_marks CHECK (max_marks > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE submissions (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  assignment_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'not_started',
  body TEXT NULL,
  attachments JSON NULL,
  submitted_at DATETIME(3) NULL,
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_submission_once (assignment_id, learner_id),
  UNIQUE KEY uq_submissions_id_org (id, org_id),
  KEY idx_submissions_learner (learner_id, status),
  CONSTRAINT fk_sub_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_sub_assign FOREIGN KEY (assignment_id, org_id) REFERENCES assignments (id, org_id),
  CONSTRAINT fk_sub_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT chk_sub_status CHECK (status IN ('not_started','draft','submitted','late','evaluated','returned'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------ PHASE 3: ASSESSMENT ------------------------
CREATE TABLE quizzes (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  instructions TEXT NULL,
  time_limit_minutes INT NULL,
  max_attempts INT NOT NULL DEFAULT 1,
  opens_at DATETIME(3) NULL,
  closes_at DATETIME(3) NULL,
  created_by VARCHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_quizzes_id_org (id, org_id),
  CONSTRAINT fk_quiz_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_quiz_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_quiz_user FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE questions (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  quiz_id VARCHAR(36) NOT NULL,
  kind VARCHAR(8) NOT NULL,
  prompt TEXT NOT NULL,
  options JSON NULL,
  answer_key JSON NULL,
  marks DECIMAL(6,2) NOT NULL DEFAULT 1,
  position INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_q_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_q_quiz FOREIGN KEY (quiz_id, org_id) REFERENCES quizzes (id, org_id),
  CONSTRAINT chk_q_kind CHECK (kind IN ('single','multiple','short','long'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quiz_attempts (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  quiz_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  answers JSON NULL,
  started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  submitted_at DATETIME(3) NULL,
  score DECIMAL(8,2) NULL,
  CONSTRAINT fk_qa_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_qa_quiz FOREIGN KEY (quiz_id, org_id) REFERENCES quizzes (id, org_id),
  CONSTRAINT fk_qa_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Every graded item (assignment, quiz, project, manual activity) is a SCORE for a learner in a batch.
CREATE TABLE scores (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  teacher_user_id VARCHAR(36) NOT NULL,
  source_type VARCHAR(12) NOT NULL,
  source_id VARCHAR(36) NULL,
  activity_name VARCHAR(255) NOT NULL,
  category VARCHAR(60) NULL,
  score DECIMAL(8,2) NOT NULL,
  max_score DECIMAL(8,2) NOT NULL,
  feedback TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  source_key VARCHAR(36) GENERATED ALWAYS AS (IF(source_id IS NULL, NULL, source_id)) STORED,
  UNIQUE KEY uq_scores_id_org (id, org_id),
  KEY idx_scores_learner (learner_id, created_at),
  KEY idx_scores_batch (batch_id, source_type),
  UNIQUE KEY uq_scores_source (learner_id, batch_id, source_type, source_key),
  CONSTRAINT fk_scores_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_scores_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_scores_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_scores_teacher FOREIGN KEY (teacher_user_id) REFERENCES users (id),
  CONSTRAINT chk_score_nonneg CHECK (score >= 0),
  CONSTRAINT chk_score_max CHECK (max_score > 0),
  CONSTRAINT chk_score_src CHECK (source_type IN ('assignment','quiz','project','activity'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE score_history (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  score_id VARCHAR(36) NOT NULL,
  changed_by VARCHAR(36) NOT NULL,
  action VARCHAR(8) NOT NULL,
  previous_score DECIMAL(8,2) NULL,
  new_score DECIMAL(8,2) NULL,
  previous_max DECIMAL(8,2) NULL,
  new_max DECIMAL(8,2) NULL,
  previous_feedback TEXT NULL,
  new_feedback TEXT NULL,
  changed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_score_history_score (score_id, changed_at),
  CONSTRAINT fk_sh_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_sh_score FOREIGN KEY (score_id, org_id) REFERENCES scores (id, org_id),
  CONSTRAINT fk_sh_user FOREIGN KEY (changed_by) REFERENCES users (id),
  CONSTRAINT chk_sh_action CHECK (action IN ('created','updated','deleted'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------ PHASE 4: GAMIFICATION ----------------------
CREATE TABLE levels (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  level_no INT NOT NULL,
  name VARCHAR(80) NOT NULL,
  min_xp INT NOT NULL,
  UNIQUE KEY uq_levels_no (org_id, level_no),
  UNIQUE KEY uq_levels_xp (org_id, min_xp),
  CONSTRAINT fk_levels_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT chk_level_xp CHECK (min_xp >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE badges (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(500) NULL,
  icon VARCHAR(60) NULL,
  category VARCHAR(60) NULL,
  xp_reward INT NOT NULL DEFAULT 0,
  criteria VARCHAR(500) NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'active',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_badges_name (org_id, name),
  UNIQUE KEY uq_badges_id_org (id, org_id),
  CONSTRAINT fk_badges_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT chk_badge_status CHECK (status IN ('active','inactive','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE learner_badges (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  badge_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NULL,
  awarded_by VARCHAR(36) NOT NULL,
  reason VARCHAR(500) NULL,
  awarded_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  revoked_at DATETIME(3) NULL,
  active_key VARCHAR(100) GENERATED ALWAYS AS (IF(revoked_at IS NULL, CONCAT(learner_id, ':', badge_id, ':', IFNULL(batch_id, '-')), NULL)) STORED,
  UNIQUE KEY uq_learner_badge_once (active_key),
  CONSTRAINT fk_lb_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_lb_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_lb_badge FOREIGN KEY (badge_id, org_id) REFERENCES badges (id, org_id),
  CONSTRAINT fk_lb_user FOREIGN KEY (awarded_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- XP is a LEDGER. Balance = SUM(points). learners.xp_cached (added in that migration) is a trigger-maintained cache.
CREATE TABLE xp_transactions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NULL,
  points INT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  source_type VARCHAR(40) NULL,
  source_id VARCHAR(80) NULL,
  created_by VARCHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_xp_learner (learner_id, created_at),
  KEY idx_xp_batch (batch_id, created_at),
  CONSTRAINT fk_xp_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_xp_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_xp_user FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_xp_points CHECK (points <> 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------ PHASE 5: ATTENDANCE & PARENT ---------------
CREATE TABLE class_sessions (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  title VARCHAR(255) NULL,
  starts_at DATETIME(3) NOT NULL,
  ends_at DATETIME(3) NULL,
  meeting_provider VARCHAR(12) NULL,
  meeting_url VARCHAR(1000) NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'scheduled',
  created_by VARCHAR(36) NULL,
  UNIQUE KEY uq_sessions_id_org (id, org_id),
  KEY idx_sessions_batch_time (batch_id, starts_at),
  CONSTRAINT fk_sess_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_sess_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_sess_user FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_sess_status CHECK (status IN ('scheduled','started','completed','cancelled')),
  CONSTRAINT chk_sess_provider CHECK (meeting_provider IS NULL OR meeting_provider IN ('google_meet','zoom','webrtc','other'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attendance is always tied to a class session of ONE batch.
CREATE TABLE attendance (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  status VARCHAR(8) NOT NULL,
  marked_by VARCHAR(36) NOT NULL,
  marked_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  note VARCHAR(300) NULL,
  UNIQUE KEY uq_attendance_once (session_id, learner_id),
  KEY idx_attendance_learner (learner_id, batch_id),
  CONSTRAINT fk_att_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_att_session FOREIGN KEY (session_id, org_id) REFERENCES class_sessions (id, org_id),
  CONSTRAINT fk_att_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_att_user FOREIGN KEY (marked_by) REFERENCES users (id),
  CONSTRAINT chk_att_status CHECK (status IN ('present','absent','late','excused'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE notifications (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  kind VARCHAR(40) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(1000) NULL,
  link VARCHAR(500) NULL,
  read_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_notifications_user (user_id, read_at, created_at),
  CONSTRAINT fk_notif_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------ PHASE 6: CRM -------------------------------
CREATE TABLE tags (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  name VARCHAR(80) NOT NULL,
  color VARCHAR(20) NULL,
  UNIQUE KEY uq_tags_name (org_id, name),
  UNIQUE KEY uq_tags_id_org (id, org_id),
  CONSTRAINT fk_tags_org FOREIGN KEY (org_id) REFERENCES organizations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE learner_tags (
  learner_id VARCHAR(36) NOT NULL,
  tag_id VARCHAR(36) NOT NULL,
  org_id VARCHAR(36) NOT NULL,
  added_by VARCHAR(36) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (learner_id, tag_id),
  KEY idx_learner_tags_tag (tag_id),
  CONSTRAINT fk_lt_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_lt_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_lt_tag FOREIGN KEY (tag_id, org_id) REFERENCES tags (id, org_id),
  CONSTRAINT fk_lt_user FOREIGN KEY (added_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ONE CRM record per learner: a lead IS a learner profile, so conversion never copies data.
CREATE TABLE crm_leads (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  lead_source VARCHAR(80) NULL,
  lead_status VARCHAR(16) NOT NULL DEFAULT 'new',
  interested_program_id VARCHAR(36) NULL,
  interested_course_id VARCHAR(36) NULL,
  interested_batch_id VARCHAR(36) NULL,
  counsellor_user_id VARCHAR(36) NULL,
  temperature VARCHAR(4) NULL,
  next_follow_up_at DATETIME(3) NULL,
  notes TEXT NULL,
  converted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_leads_learner (learner_id),
  UNIQUE KEY uq_leads_id_org (id, org_id),
  KEY idx_leads_status (org_id, lead_status),
  KEY idx_leads_counsellor (counsellor_user_id, next_follow_up_at),
  CONSTRAINT fk_leads_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_leads_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_leads_counsellor FOREIGN KEY (counsellor_user_id) REFERENCES users (id),
  CONSTRAINT chk_lead_status CHECK (lead_status IN ('new','contacted','interested','demo_scheduled','demo_attended','follow_up','converted','not_interested','lost')),
  CONSTRAINT chk_lead_temp CHECK (temperature IS NULL OR temperature IN ('cold','warm','hot'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE crm_activities (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  lead_id VARCHAR(36) NULL,
  type VARCHAR(40) NOT NULL,
  description TEXT NULL,
  staff_user_id VARCHAR(36) NULL,
  occurred_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  next_follow_up_at DATETIME(3) NULL,
  KEY idx_crm_activities_learner (learner_id, occurred_at),
  CONSTRAINT fk_cact_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_cact_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_cact_staff FOREIGN KEY (staff_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE follow_ups (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  assigned_to VARCHAR(36) NOT NULL,
  due_at DATETIME(3) NOT NULL,
  note VARCHAR(500) NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'open',
  completed_at DATETIME(3) NULL,
  KEY idx_follow_ups_due (assigned_to, status, due_at),
  CONSTRAINT fk_fu_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_fu_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_fu_user FOREIGN KEY (assigned_to) REFERENCES users (id),
  CONSTRAINT chk_fu_status CHECK (status IN ('open','done','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------ PHASE 7: COMMUNICATION ---------------------
CREATE TABLE whatsapp_templates (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  aisensy_campaign_name VARCHAR(160) NOT NULL,
  use_case VARCHAR(40) NOT NULL,
  body_preview TEXT NULL,
  variable_names JSON NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'active',
  UNIQUE KEY uq_wat_name (org_id, name),
  UNIQUE KEY uq_wat_id_org (id, org_id),
  CONSTRAINT fk_wat_org FOREIGN KEY (org_id) REFERENCES organizations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE whatsapp_campaigns (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  name VARCHAR(160) NOT NULL,
  template_id VARCHAR(36) NOT NULL,
  selector JSON NOT NULL,
  variables JSON NULL,
  scheduled_at DATETIME(3) NULL,
  created_by VARCHAR(36) NOT NULL,
  confirmed_at DATETIME(3) NULL,
  confirmed_by VARCHAR(36) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  total_recipients INT NOT NULL DEFAULT 0,
  batch_memberships INT NOT NULL DEFAULT 0,
  duplicates_removed INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_wac_id_org (id, org_id),
  KEY idx_campaigns_status (org_id, status, scheduled_at),
  CONSTRAINT fk_wac_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_wac_template FOREIGN KEY (template_id, org_id) REFERENCES whatsapp_templates (id, org_id),
  CONSTRAINT fk_wac_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_wac_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id),
  CONSTRAINT chk_wac_status CHECK (status IN ('draft','scheduled','processing','completed','partially_failed','failed','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- SNAPSHOT of recipients at confirmation time: one row per UNIQUE learner and per UNIQUE phone (siblings sharing a parent phone get one message).
CREATE TABLE whatsapp_recipients (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  campaign_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  parent_id VARCHAR(36) NULL,
  phone VARCHAR(20) NOT NULL,
  variables JSON NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  next_attempt_at DATETIME(3) NULL,
  last_error VARCHAR(500) NULL,
  UNIQUE KEY uq_war_learner (campaign_id, learner_id),
  UNIQUE KEY uq_war_phone (campaign_id, phone),
  KEY idx_wa_recipients_queue (status, next_attempt_at),
  CONSTRAINT fk_war_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_war_campaign FOREIGN KEY (campaign_id, org_id) REFERENCES whatsapp_campaigns (id, org_id),
  CONSTRAINT fk_war_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT chk_war_status CHECK (status IN ('pending','queued','sent','delivered','read','failed','cancelled','skipped'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE whatsapp_messages (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  recipient_id VARCHAR(36) NULL,
  campaign_id VARCHAR(36) NULL,
  provider_message_id VARCHAR(120) NULL,
  direction VARCHAR(8) NOT NULL DEFAULT 'outbound',
  status VARCHAR(20) NOT NULL,
  error_code VARCHAR(40) NULL,
  error_message VARCHAR(500) NULL,
  payload JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_wa_messages_provider (provider_message_id),
  CONSTRAINT fk_wam_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_wam_recipient FOREIGN KEY (recipient_id) REFERENCES whatsapp_recipients (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE webhook_events (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  provider VARCHAR(30) NOT NULL,
  event_id VARCHAR(120) NULL,
  payload JSON NOT NULL,
  processed_at DATETIME(3) NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_webhook_event (provider, event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------ PHASE 6/9: FINANCE -------------------------
CREATE TABLE invoices (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  learner_id VARCHAR(36) NOT NULL,
  batch_id VARCHAR(36) NULL,
  invoice_no VARCHAR(40) NOT NULL,
  amount_paise BIGINT NOT NULL,
  due_on DATE NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_invoice_no (org_id, invoice_no),
  UNIQUE KEY uq_invoices_id_org (id, org_id),
  CONSTRAINT fk_inv_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_inv_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT chk_inv_amount CHECK (amount_paise >= 0),
  CONSTRAINT chk_inv_status CHECK (status IN ('pending','partially_paid','paid','overdue','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  invoice_id VARCHAR(36) NOT NULL,
  amount_paise BIGINT NOT NULL,
  method VARCHAR(30) NOT NULL,
  reference VARCHAR(120) NULL,
  paid_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  recorded_by VARCHAR(36) NULL,
  KEY idx_payments_invoice (invoice_id),
  CONSTRAINT fk_pay_org FOREIGN KEY (org_id) REFERENCES organizations (id),
  CONSTRAINT fk_pay_invoice FOREIGN KEY (invoice_id, org_id) REFERENCES invoices (id, org_id),
  CONSTRAINT fk_pay_user FOREIGN KEY (recorded_by) REFERENCES users (id),
  CONSTRAINT chk_pay_amount CHECK (amount_paise > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
