-- ============================================================================
-- Robokalam Learner OS — Migration 001: Phase 1 Foundation (MySQL 8 / MariaDB 10.6+)
-- Tenancy, auth, RBAC, catalog, master learner DB, parents, batches,
-- learner/teacher batch memberships, activity timeline, audit log.
--
-- Core invariant: ONE learner = ONE row in `learners`. Batch participation is
-- expressed ONLY through `learner_batch_memberships` (unique learner_id+batch_id).
-- Every business table carries org_id and composite foreign keys (id, org_id)
-- prevent cross-tenant references at the database level.
--
-- MySQL notes: ids are VARCHAR(36) UUIDs generated by the application; "partial"
-- unique indexes are emulated with STORED generated columns that are NULL when the
-- rule does not apply (a UNIQUE index ignores NULLs); times are UTC DATETIME(3).
-- ============================================================================

CREATE TABLE organizations (
  id            VARCHAR(36) NOT NULL PRIMARY KEY,
  name          VARCHAR(160) NOT NULL,
  slug          VARCHAR(50) NOT NULL,
  code_prefix   VARCHAR(6) NOT NULL DEFAULT 'RK',
  timezone      VARCHAR(60) NOT NULL DEFAULT 'Asia/Kolkata',
  status        VARCHAR(12) NOT NULL DEFAULT 'active',
  settings      JSON NULL,
  created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at    DATETIME(3) NULL,
  UNIQUE KEY uq_organizations_slug (slug),
  CONSTRAINT chk_org_slug CHECK (slug COLLATE utf8mb4_bin REGEXP '^[a-z0-9][a-z0-9-]{1,48}$'),
  CONSTRAINT chk_org_prefix CHECK (code_prefix COLLATE utf8mb4_bin REGEXP '^[A-Z0-9]{2,6}$'),
  CONSTRAINT chk_org_status CHECK (status IN ('active','suspended','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Per-organization counters for human readable ids (RK-LRN-000124).
CREATE TABLE org_counters (
  org_id       VARCHAR(36) NOT NULL,
  counter_key  VARCHAR(40) NOT NULL,
  value        BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (org_id, counter_key),
  CONSTRAINT fk_counters_org FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE branches (
  id          VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id      VARCHAR(36) NOT NULL,
  name        VARCHAR(160) NOT NULL,
  code        VARCHAR(20) NOT NULL,
  city        VARCHAR(100) NULL,
  address     VARCHAR(400) NULL,
  status      VARCHAR(12) NOT NULL DEFAULT 'active',
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at  DATETIME(3) NULL,
  UNIQUE KEY uq_branches_org_code (org_id, code),
  UNIQUE KEY uq_branches_id_org (id, org_id),
  CONSTRAINT fk_branches_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT chk_branch_status CHECK (status IN ('active','inactive','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Identity & RBAC
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id                   VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id               VARCHAR(36) NULL,                            -- NULL only for platform super admins
  email                VARCHAR(190) NOT NULL,
  mobile               VARCHAR(20) NULL,
  password_hash        VARCHAR(255) NOT NULL,
  full_name            VARCHAR(160) NOT NULL,
  status               VARCHAR(12) NOT NULL DEFAULT 'active',
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  failed_login_count   INT NOT NULL DEFAULT 0,
  locked_until         DATETIME(3) NULL,
  last_login_at        DATETIME(3) NULL,
  created_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at           DATETIME(3) NULL,
  email_key            VARCHAR(190) GENERATED ALWAYS AS (IF(deleted_at IS NULL, email, NULL)) STORED,
  UNIQUE KEY uq_users_email (email_key),
  UNIQUE KEY uq_users_id_org (id, org_id),
  KEY idx_users_org (org_id),
  KEY idx_users_mobile (mobile),
  CONSTRAINT fk_users_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT chk_user_status CHECK (status IN ('active','disabled','invited'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE roles (
  id           VARCHAR(36) NOT NULL PRIMARY KEY,
  code         VARCHAR(40) NOT NULL,
  name         VARCHAR(80) NOT NULL,
  description  VARCHAR(255) NULL,
  is_system    BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE KEY uq_roles_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE permissions (
  id           VARCHAR(36) NOT NULL PRIMARY KEY,
  code         VARCHAR(60) NOT NULL,
  description  VARCHAR(255) NULL,
  UNIQUE KEY uq_permissions_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE role_permissions (
  role_id        VARCHAR(36) NOT NULL,
  permission_id  VARCHAR(36) NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A user can hold several roles; branch_id optionally narrows the scope of a role.
CREATE TABLE user_roles (
  id          VARCHAR(36) NOT NULL PRIMARY KEY,
  user_id     VARCHAR(36) NOT NULL,
  role_id     VARCHAR(36) NOT NULL,
  org_id      VARCHAR(36) NULL,
  branch_id   VARCHAR(36) NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  branch_key  VARCHAR(36) GENERATED ALWAYS AS (IF(branch_id IS NULL, role_id, branch_id)) STORED,
  UNIQUE KEY uq_user_roles (user_id, role_id, branch_key),
  KEY idx_user_roles_user (user_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT fk_ur_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_ur_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE auth_sessions (
  id                  VARCHAR(36) NOT NULL PRIMARY KEY,
  user_id             VARCHAR(36) NOT NULL,
  refresh_token_hash  VARCHAR(64) NOT NULL,
  user_agent          VARCHAR(300) NULL,
  ip                  VARCHAR(64) NULL,
  expires_at          DATETIME(3) NOT NULL,
  revoked_at          DATETIME(3) NULL,
  created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_sessions_hash (refresh_token_hash),
  KEY idx_auth_sessions_user (user_id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Catalog: programs → courses
-- ---------------------------------------------------------------------------
CREATE TABLE programs (
  id           VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id       VARCHAR(36) NOT NULL,
  name         VARCHAR(160) NOT NULL,
  code         VARCHAR(20) NOT NULL,
  description  VARCHAR(1000) NULL,
  status       VARCHAR(12) NOT NULL DEFAULT 'active',
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at   DATETIME(3) NULL,
  UNIQUE KEY uq_programs_org_code (org_id, code),
  UNIQUE KEY uq_programs_id_org (id, org_id),
  CONSTRAINT fk_programs_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT chk_program_status CHECK (status IN ('active','inactive','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE courses (
  id           VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id       VARCHAR(36) NOT NULL,
  program_id   VARCHAR(36) NOT NULL,
  name         VARCHAR(160) NOT NULL,
  code         VARCHAR(20) NOT NULL,
  description  VARCHAR(1000) NULL,
  status       VARCHAR(12) NOT NULL DEFAULT 'active',
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at   DATETIME(3) NULL,
  UNIQUE KEY uq_courses_org_code (org_id, code),
  UNIQUE KEY uq_courses_id_org (id, org_id),
  KEY idx_courses_program (program_id),
  CONSTRAINT fk_courses_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_courses_program FOREIGN KEY (program_id, org_id) REFERENCES programs (id, org_id),
  CONSTRAINT chk_course_status CHECK (status IN ('active','inactive','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- People: parents and the MASTER learner table
-- ---------------------------------------------------------------------------
CREATE TABLE parents (
  id          VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id      VARCHAR(36) NOT NULL,
  user_id     VARCHAR(36) NULL,
  full_name   VARCHAR(160) NOT NULL,
  mobile      VARCHAR(20) NULL,
  email       VARCHAR(190) NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at  DATETIME(3) NULL,
  mobile_key  VARCHAR(20) GENERATED ALWAYS AS (IF(deleted_at IS NULL, mobile, NULL)) STORED,
  UNIQUE KEY uq_parents_id_org (id, org_id),
  -- Siblings share ONE parent record: a parent mobile is unique per organization.
  UNIQUE KEY uq_parents_org_mobile (org_id, mobile_key),
  KEY idx_parents_org_email (org_id, email),
  KEY idx_parents_user (user_id),
  CONSTRAINT fk_parents_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_parents_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE learners (
  id             VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id         VARCHAR(36) NOT NULL,
  branch_id      VARCHAR(36) NULL,
  user_id        VARCHAR(36) NULL,
  learner_code   VARCHAR(30) NOT NULL,                -- e.g. RK-LRN-000124 (immutable)
  full_name      VARCHAR(160) NOT NULL,
  mobile         VARCHAR(20) NULL,                    -- normalised: +91XXXXXXXXXX
  email          VARCHAR(190) NULL,
  date_of_birth  DATE NULL,
  gender         VARCHAR(12) NULL,
  school         VARCHAR(200) NULL,
  location       VARCHAR(200) NULL,
  photo_url      VARCHAR(500) NULL,
  status         VARCHAR(12) NOT NULL DEFAULT 'active',
  enrolled_on    DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_by     VARCHAR(36) NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at     DATETIME(3) NULL,
  mobile_key     VARCHAR(20) GENERATED ALWAYS AS (IF(deleted_at IS NULL, mobile, NULL)) STORED,
  email_key      VARCHAR(190) GENERATED ALWAYS AS (IF(deleted_at IS NULL, email, NULL)) STORED,
  UNIQUE KEY uq_learners_org_code (org_id, learner_code),
  UNIQUE KEY uq_learners_id_org (id, org_id),
  UNIQUE KEY uq_learners_org_mobile (org_id, mobile_key),
  UNIQUE KEY uq_learners_org_email (org_id, email_key),
  KEY idx_learners_org_status (org_id, status),
  KEY idx_learners_org_name (org_id, full_name, id),
  KEY idx_learners_org_created (org_id, created_at, id),
  KEY idx_learners_org_enrolled (org_id, enrolled_on),
  KEY idx_learners_branch (branch_id),
  KEY idx_learners_user (user_id),
  CONSTRAINT fk_learners_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_learners_branch FOREIGN KEY (branch_id, org_id) REFERENCES branches (id, org_id),
  CONSTRAINT fk_learners_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_learners_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT chk_learner_status CHECK (status IN ('active','inactive','archived')),
  CONSTRAINT chk_learner_gender CHECK (gender IS NULL OR gender IN ('female','male','other','undisclosed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE learner_parents (
  learner_id    VARCHAR(36) NOT NULL,
  parent_id     VARCHAR(36) NOT NULL,
  org_id        VARCHAR(36) NOT NULL,
  relationship  VARCHAR(30) NOT NULL DEFAULT 'guardian',
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  primary_key_  VARCHAR(36) GENERATED ALWAYS AS (IF(is_primary, learner_id, NULL)) STORED,
  PRIMARY KEY (learner_id, parent_id),
  UNIQUE KEY uq_learner_primary_parent (primary_key_),
  KEY idx_learner_parents_parent (parent_id),
  CONSTRAINT fk_lp_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_lp_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_lp_parent FOREIGN KEY (parent_id, org_id) REFERENCES parents (id, org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Batches and memberships
-- ---------------------------------------------------------------------------
CREATE TABLE batches (
  id             VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id         VARCHAR(36) NOT NULL,
  branch_id      VARCHAR(36) NULL,
  program_id     VARCHAR(36) NOT NULL,
  course_id      VARCHAR(36) NOT NULL,
  batch_code     VARCHAR(30) NOT NULL,                  -- e.g. RK-BAT-0042
  name           VARCHAR(160) NOT NULL,
  academic_year  VARCHAR(20) NOT NULL,                  -- e.g. 2026-27
  start_date     DATE NULL,
  end_date       DATE NULL,
  schedule       JSON NULL,                             -- {days:[1,3], start:"17:00", end:"18:30", mode:"online"}
  capacity       INT NULL,
  status         VARCHAR(12) NOT NULL DEFAULT 'upcoming',
  created_by     VARCHAR(36) NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at     DATETIME(3) NULL,
  UNIQUE KEY uq_batches_org_code (org_id, batch_code),
  UNIQUE KEY uq_batches_id_org (id, org_id),
  KEY idx_batches_org_status (org_id, status),
  KEY idx_batches_course (course_id),
  KEY idx_batches_program (program_id),
  KEY idx_batches_branch (branch_id),
  KEY idx_batches_year (org_id, academic_year),
  CONSTRAINT fk_batches_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_batches_branch FOREIGN KEY (branch_id, org_id) REFERENCES branches (id, org_id),
  CONSTRAINT fk_batches_program FOREIGN KEY (program_id, org_id) REFERENCES programs (id, org_id),
  CONSTRAINT fk_batches_course FOREIGN KEY (course_id, org_id) REFERENCES courses (id, org_id),
  CONSTRAINT fk_batches_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT chk_batch_status CHECK (status IN ('upcoming','active','completed','archived')),
  CONSTRAINT chk_batch_capacity CHECK (capacity IS NULL OR capacity > 0),
  CONSTRAINT chk_batch_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- THE learner ↔ batch relationship. One row per (learner, batch), ever.
-- Re-joining a batch re-activates the same row; history lives in learner_activity.
CREATE TABLE learner_batch_memberships (
  id           VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id       VARCHAR(36) NOT NULL,
  learner_id   VARCHAR(36) NOT NULL,
  batch_id     VARCHAR(36) NOT NULL,
  status       VARCHAR(12) NOT NULL DEFAULT 'active',
  joined_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  left_at      DATETIME(3) NULL,
  left_reason  VARCHAR(200) NULL,
  enrolled_by  VARCHAR(36) NULL,
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_learner_batch (learner_id, batch_id),
  KEY idx_lbm_batch_status (batch_id, status),
  KEY idx_lbm_learner_status (learner_id, status),
  KEY idx_lbm_org (org_id),
  CONSTRAINT fk_lbm_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_lbm_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_lbm_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_lbm_enrolled_by FOREIGN KEY (enrolled_by) REFERENCES users(id),
  CONSTRAINT chk_lbm_status CHECK (status IN ('active','completed','left','transferred'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE teacher_batch_memberships (
  id               VARCHAR(36) NOT NULL PRIMARY KEY,
  org_id           VARCHAR(36) NOT NULL,
  batch_id         VARCHAR(36) NOT NULL,
  teacher_user_id  VARCHAR(36) NOT NULL,
  role             VARCHAR(8) NOT NULL DEFAULT 'lead',
  status           VARCHAR(8) NOT NULL DEFAULT 'active',
  assigned_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  removed_at       DATETIME(3) NULL,
  assigned_by      VARCHAR(36) NULL,
  lead_key         VARCHAR(36) GENERATED ALWAYS AS (IF(role = 'lead' AND status = 'active', batch_id, NULL)) STORED,
  UNIQUE KEY uq_teacher_batch (batch_id, teacher_user_id),
  -- At most one active lead teacher per batch.
  UNIQUE KEY uq_tbm_one_lead (lead_key),
  KEY idx_tbm_teacher_status (teacher_user_id, status),
  KEY idx_tbm_batch_status (batch_id, status),
  CONSTRAINT fk_tbm_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_tbm_batch FOREIGN KEY (batch_id, org_id) REFERENCES batches (id, org_id),
  CONSTRAINT fk_tbm_teacher FOREIGN KEY (teacher_user_id, org_id) REFERENCES users (id, org_id),
  CONSTRAINT fk_tbm_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id),
  CONSTRAINT chk_tbm_role CHECK (role IN ('lead','co')),
  CONSTRAINT chk_tbm_status CHECK (status IN ('active','removed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Learner activity timeline & audit log
-- ---------------------------------------------------------------------------
CREATE TABLE learner_activity (
  id             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  org_id         VARCHAR(36) NOT NULL,
  learner_id     VARCHAR(36) NOT NULL,
  batch_id       VARCHAR(36) NULL,
  type           VARCHAR(40) NOT NULL,        -- learner.created, batch.joined, batch.left, batch.transferred_in, ...
  title          VARCHAR(255) NOT NULL,
  description    VARCHAR(500) NULL,
  meta           JSON NULL,
  actor_user_id  VARCHAR(36) NULL,
  occurred_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_activity_learner_time (learner_id, occurred_at, id),
  KEY idx_activity_org_time (org_id, occurred_at),
  CONSTRAINT fk_activity_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_activity_learner FOREIGN KEY (learner_id, org_id) REFERENCES learners (id, org_id),
  CONSTRAINT fk_activity_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_logs (
  id             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  org_id         VARCHAR(36) NULL,
  actor_user_id  VARCHAR(36) NULL,
  actor_email    VARCHAR(190) NULL,
  action         VARCHAR(60) NOT NULL,
  entity_type    VARCHAR(40) NOT NULL,
  entity_id      VARCHAR(80) NULL,
  previous_data  JSON NULL,
  new_data       JSON NULL,
  ip             VARCHAR(64) NULL,
  user_agent     VARCHAR(300) NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_audit_org_time (org_id, created_at),
  KEY idx_audit_entity (entity_type, entity_id),
  KEY idx_audit_actor (actor_user_id),
  CONSTRAINT fk_audit_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Seed: system roles and permissions (static reference data)
-- ---------------------------------------------------------------------------
INSERT INTO roles (id, code, name, description) VALUES
  (UUID(), 'super_admin',  'Super Admin',         'Platform owner; manages organizations'),
  (UUID(), 'org_admin',    'Organization Admin',  'Full control inside one organization'),
  (UUID(), 'branch_admin', 'Branch Admin',        'Manages learners and batches of assigned branch(es)'),
  (UUID(), 'teacher',      'Teacher',             'Works with assigned batches and their learners'),
  (UUID(), 'counsellor',   'Counsellor',          'Leads, CRM and follow-ups'),
  (UUID(), 'accountant',   'Accountant',          'Payments, invoices and fees'),
  (UUID(), 'learner',      'Learner',             'Own data only'),
  (UUID(), 'parent',       'Parent',              'Linked children only');

INSERT INTO permissions (id, code, description) VALUES
  (UUID(), 'org:manage',         'Update organization settings'),
  (UUID(), 'branch:manage',      'Create and edit branches'),
  (UUID(), 'catalog:read',       'View programs, courses and branches'),
  (UUID(), 'catalog:manage',     'Create and edit programs and courses'),
  (UUID(), 'user:manage',        'Create and manage staff users and roles'),
  (UUID(), 'teacher:read',       'View teachers'),
  (UUID(), 'learner:read',       'View learners in scope'),
  (UUID(), 'learner:create',     'Create learners'),
  (UUID(), 'learner:update',     'Edit learner profile'),
  (UUID(), 'learner:delete',     'Archive and restore learners'),
  (UUID(), 'learner:export',     'Export learner data'),
  (UUID(), 'learner:bulk',       'Run bulk actions on learners'),
  (UUID(), 'learner:login',      'Create learner/parent portal logins'),
  (UUID(), 'parent:read',        'View parents'),
  (UUID(), 'parent:manage',      'Create and edit parents'),
  (UUID(), 'batch:read',         'View batches in scope'),
  (UUID(), 'batch:create',       'Create batches'),
  (UUID(), 'batch:update',       'Edit batches'),
  (UUID(), 'batch:enroll',       'Add and remove learners from batches'),
  (UUID(), 'batch:assign_teacher','Assign teachers to batches'),
  (UUID(), 'selection:resolve',  'Use the batch selection engine'),
  (UUID(), 'dashboard:view',     'View role dashboard'),
  (UUID(), 'audit:read',         'View audit logs'),
  (UUID(), 'portal:learner',     'Learner self-service portal'),
  (UUID(), 'portal:parent',      'Parent self-service portal');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON
  (r.code IN ('super_admin','org_admin'))
  OR (r.code = 'branch_admin' AND p.code IN ('catalog:read','catalog:manage','user:manage','teacher:read','learner:read','learner:create','learner:update','learner:delete','learner:export','learner:bulk','learner:login','parent:read','parent:manage','batch:read','batch:create','batch:update','batch:enroll','batch:assign_teacher','selection:resolve','dashboard:view','audit:read'))
  OR (r.code = 'teacher' AND p.code IN ('catalog:read','teacher:read','learner:read','parent:read','batch:read','selection:resolve','dashboard:view'))
  OR (r.code = 'counsellor' AND p.code IN ('catalog:read','teacher:read','learner:read','learner:create','learner:update','learner:export','parent:read','parent:manage','batch:read','batch:enroll','selection:resolve','dashboard:view'))
  OR (r.code = 'accountant' AND p.code IN ('catalog:read','learner:read','parent:read','batch:read','dashboard:view'))
  OR (r.code = 'learner' AND p.code IN ('portal:learner','dashboard:view'))
  OR (r.code = 'parent' AND p.code IN ('portal:parent','dashboard:view'));
